[package]
name = "workspace"
version = "0.1.0"
authors = ["yoshimura <yoshimura@freemind.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }