version: '3'
services:
    rust:
        image: rust:1.50
        volumes:
          - /rust
        environment:
          - USER=`${USER}`
        working_dir: /rust
        stdin_open: true